### ISSUE TITLE
I cannot execute "docker-compose run" from MacOS.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-common#1]
I tried to pull stip-common and run docker-compose run.
But it failed because of something wrong about file permissions.
So I removed volumes option from docker-compose.yml and restart.
I could run S-TIP successfully.
I am not sure but it may be miss configuration about MacOS docker or docker-compose.

If you have any resolution, plaese tell me.
Thx!

**Comment by ykoji8681** [comment]
@stmtstk , I have encountered the same issue on Windows (Docker for Windows).
It seems that the workaround is invalidating volumes.

**Comment by stmtstk** [comment]
https://hub.docker.com/_/mongo

> WARNING (Windows & OS X): The default Docker setup on Windows and OS X uses a VirtualBox VM to host the Docker daemon. Unfortunately, the mechanism VirtualBox uses to share folders between the host system and the Docker container is not compatible with the memory mapped files used by MongoDB (see vbox bug, docs.mongodb.org and related jira.mongodb.org bug). This means that it is not possible to run a MongoDB container with the data directory mapped to the host.

It seems to be a specification of a docker mongo image.
So please close this issue.

**Comment by ykoji8681** [comment]
Thanks for researching that, @stmtstk .
close #1
