### ISSUE TITLE
Could not find a stix-validator==2.0.0.dev1 in Docker build.

### ISSUE THREAD

**Issue by tkhsknsk** [s-tip/stip-common#15]
ローカル環境でS-TIPを環境構築すべく、Docker builidコマンドで実行したところ
以下のエラーメッセージで中断してしまいます。
Could not find a version that satisfies the requirement stix-validator==2.0.0.dev1

```
Collecting stix-validator==2.0.0.dev1 (from -r /stip-common/install_scripts/requirements_rs.txt (line 9))
  Could not find a version that satisfies the requirement stix-validator==2.0.0.dev1 (from -r /stip-common/install_scripts/requirements_rs.txt (line 9)) (from versions: 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2.0, 2.3.0, 2.4.0, 2.5.0.dev0, 2.5.0)
No matching distribution found for stix-validator==2.0.0.dev1 (from -r /stip-common/install_scripts/requirements_rs.txt (line 9))
The command '/bin/sh -c pip install -r ${SCRIPTS_DIR}/requirements_rs.txt -r ${SCRIPTS_DIR}/requirements_gv.txt -r ${SCRIPTS_DIR}/requirements_sns.txt' returned a non-zero code: 1
```

試しに、requirements_rs.txt、requirements_sns.txtの中身を`stix-validator==2.0.0`に直すとビルドに成功しますが、`2.0.0.dev2`でインストールされてしまいます。

**Comment by ta-hiroki** [comment]
#11 #13 ではstix2-validatorのv2.0.0.dev1をインストールしたいため、
`stix-validator==2.0.0.dev1`を追記しましたが、
stix-validatorとstix2-validatorは別のモジュールで、
stix-validatorがインストールされることでstix2-validatorも同時にインストールはされませんでした。

そのため以下の対応が必要だと思いますが問題ないでしょうか?　> @stmtstk さん @ykoji8681 さん
- requirements_sns.txt
   #11 の修正を元に戻す(`stix-validator==2.0.0.dev1`を`stix-validator`に修正)
- requirements_rs.txt
   #13 で追記した`stix-validator==2.0.0.dev1`を`stix2-validator==2.0.0.dev1`に修正
   (`stix2-elevator`のインストール時に`stix-validator==2.0.0.dev2`がインストールされてしまうため。)

**Comment by ykoji8681** [comment]
* stix-validatorの2.0.0.dev1がPypiから無くなっているのが原因でしょうか。
2.0.0で動作確認ですね。(可能なら2.5.0?)
requirements_sns.txtも要修正ですね。

* stix2-validator==2.0.0.dev1
こちらはバージョン指定しないと1.1.2が入るのですが、S-TIPで最新のSTIX2系対応のため
2.0.0.dev1指定が必要だと思います。

@stmtstk よろしいでしょうか？

**Comment by stmtstk** [comment]
@ykoji8681 @ta-hiroki @tkhsknsk 調査ありがとうございます。

@ta-hiroki さんの提案方法で修正しましょう
