### ISSUE TITLE
setup_rs.sh mongo DB

### ISSUE THREAD

**Issue by lysdexiafj** [s-tip/stip-common#21]
Hey,

Trying to install RS on Ubuntu 18.04, however in setup_rs.sh on line 48. It is trying to install the Xenial version of MongoDB.

Is this version required or can we use the Bionic Version? 

Thanks,

lysdexiafj

**Comment by ykoji8681** [comment]
Thanks, @lysdexiafj. Good catch.

We should use the Bionic version on Ubuntu 18 instead of Xenial.

It seems that MongoDB v3.4 is no longer available on Bionic repository, so I will modify the script for MongoDB v4.0.

**Comment by stmtstk** [comment]
@ykoji8681 @lysdexiafj  Thanks for your contribution!
