### ISSUE TITLE
Add handling of session during Ajax.

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-common#27]
Related issue: https://github.com/s-tip/stip-sns/issues/30

If a session timeout occurs while Ajax is running, add a function that transition to the login page.

**Comment by stmtstk** [comment]
Thanks @ta-hiroki!!

I checked your works.
I have approved and merged your pull requests into release_11.

You can close this issue.

By the way, I would like to advice about private branches.
We should remove working branches after merging.

---

対応ありがとうございます。
こちらで動作を確認して、ソースレビューを実施、release_11 に merge しました。
この Issue も閉じてもらってかまいません。
あと一つアドバイスですが、Merge が終わった後の作業用ブランチは削除したほうがいいかと思います。
git branch -a とかやってみると、たくさんリストされて、本当に必要なものがわからなくなるからです。
削除は Web UI からもできますので試してみてください。
