### ISSUE TITLE
Display a message when an user faill to login

### ISSUE THREAD

**Issue by uchimrina** [s-tip/stip-common#29]

**Comment by uchimrina** [comment]
@stmtstk 
Where do you want the message to appear?

**Comment by stmtstk** [comment]
@uchimrina 

It Just "Login Failed".

---

"Login Failed" でいいです

**Comment by uchimrina** [comment]
I created an issue because it needs to be fixed in other repositories.

---  

GV,RS,SNSのリポジトリでも修正が必要なので、issueを作成しました。

**Comment by uchimrina** [comment]
Which design would you like?

![image](https://user-images.githubusercontent.com/50690496/88141180-0dc81600-cc2e-11ea-8797-bf69ad8c0ef2.png)

**Comment by stmtstk** [comment]
@uchimrina 

Please go with "1".
