### ISSUE TITLE
Add the TOTP entry field to the login screen.

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-common#32]
On the login screen, if totp_secret filed is not None, enter a 6-digit code, and if it matches, allow login.
If totp_secret is None, 2FA does not execute and allows login.

---

ログイン画面で totp_secret filed が None 以外なら 6桁のコードを入力させ、 適合していたらログイン可能とする。
もし totp_secret filed が None であれば 2FA を行わずログイン可能。

**Comment by uchimrina** [comment]
@stmtstk 
Please check the design.
![design](https://user-images.githubusercontent.com/50690496/89493677-a2ff0900-d7ef-11ea-8fc0-0423ffa28843.PNG)

**Comment by stmtstk** [comment]
@uchimrina 

It seems to be good.
The type of the "Authentication Code" text field is "text" not "password".
Perhaps I may ask you to correct the English sentence, but for now I would like it

---

良いと思います。
Authentication Code の text field の type は password じゃなくて、text にしてください (値を masking しなくていいです)。
英文はもしかしたら修正をお願いするかもしれませんが、ひとまずその英文でお願いします。
