### ISSUE TITLE
SNS post returns error in specific cases

### ISSUE THREAD

**Issue by ykoji8681** [s-tip/stip-common#4]
In S-TIP SNS, an error occured in following cases:

1. When I create new post without Slack setting, server returns following error in /var/log/apache2/error_sns.log.

```
 AttributeError: 'NoneType' object has no attribute 'api_call'
```

2.  I cannot change icon in "Upload New Picture". 
The error message in /var/log/apache2/error_sns.log:
```
[Mon Jun 03 02:28:01.615577 2019] [wsgi:error] [pid 4403:tid 140268516189952] [remote 122.24.176.77:64368] WARNING:django.request:Not Found: /media/profile_pictures/slack_tmp.jpg
```

3. OTX Adapter returns "Internal Server Error" in SNS.

The error message in /var/log/apache2/error_sns.log:
```
[Sun Jun 02 18:55:55.601902 2019] [wsgi:error] [pid 2409:tid 140486780651264] [remote 122.24.176.77:50975] IntegrityError: (1048, "Column 'screen_affiliation' cannot be null")
```

4. When I use MISP Adapter, the icon of posts is not misp's one.

5. When an user comments to a post, the comment number is not refreshed automatically.

**Comment by stmtstk** [comment]
@ykoji8681  I guess that these issues affect some repositories. So I create same issue at each repository.
If you confirm that these issues are closed, please close this issue.
Thx!

**Comment by ykoji8681** [comment]
That works for me.
Thanks, @stmtstk !
