### ISSUE TITLE
MultIValueDictKeyError occurred.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-common#48]
When a user logout and fill `/login` or `/login_totp in an address bar directly.
MultiVauleDictKeyError occurrd.

---

ログアウトされている状態で、アドレスバーに直接 `/login/` ないし `/login_totp/` を入力して遷移するとエラーになります。
stip-common の login.py の中で、username, password field に値がないので、 `request.POST["uername"]` がなくて
エラーになっていると思います。
直接アドレスバーに入力してくるケースもあるので、この場合は、cover.html を render するようにしてください。
ちなみに `MultiVauleDictKeyError ` は

```
from django.utils.datastructures import MultiVauleDictKeyError 
```

にあります。

**Comment by tkhsknsk** [comment]
`/login/` -> MultiVauleDictKeyError
Corrected in "try_except".

`/login_totp/` -> KeyError
Corrected in get() ｍethod.

**Comment by tkhsknsk** [comment]
Approved and closed.
