### ISSUE TITLE
Polling error to STIX server

### ISSUE THREAD

**Issue by kp625544** [s-tip/stip-common#53]
While polling any STIX server we get the following error:
<img width="1440" alt="Screenshot 2020-09-09 at 5 48 41 PM" src="https://user-images.githubusercontent.com/18206620/92597235-b99ff080-f2c4-11ea-9132-98e12ed0a3c2.png">

Traceback (most recent call last):
  File "/opt/s-tip/rs/src/ctirs/poll/views.py", line 76, in start
    count = cl.poll()
  File "/opt/s-tip/rs/src/ctirs/core/taxii/taxii.py", line 152, in poll
    return self.poll_11()
  File "/opt/s-tip/rs/src/ctirs/core/taxii/taxii.py", line 190, in poll_11
    taxii_message = libtaxii.get_message_from_http_response(http_resp, poll_request.message_id)
  File "/usr/local/lib/python3.6/dist-packages/libtaxii/__init__.py", line 45, in get_message_from_http_response
    return get_message_from_urllib2_httperror(http_response, in_response_to)
  File "/usr/local/lib/python3.6/dist-packages/libtaxii/__init__.py", line 64, in get_message_from_urllib2_httperror
    response_message = six.ensure_text(http_response.read(), errors='replace')
AttributeError: module 'six' has no attribute 'ensure_text'

**Comment by stmtstk** [comment]
@kp625544 

 Thank you for using S-TIP!!

I guess that your `six` library may be old.
Please make sure your six library version like this.

```
pip freeze | grep six
```
or

```
pip3 freeze | grep six
```

if this vesrson is less than `1.12.0`, `ensure_text` is not supported.
Please update six library.

```
pip install "six>=1.12.0"
```

or 

```
pip install "six>=1.12.0"
```

**Comment by kp625544** [comment]
Yes, I got that, but issue is I m installing using docker, so how do I fix with that?

**Comment by stmtstk** [comment]
Please try this command and dive into your docker image.

```
docker exec -it <your_stip_docker_name> /bin/bash
```

I guess <your_docker_name> is  `docker_stip_1`.

After login, input a command below.

```
pip3 install "six>=1.12.0"
sudo /etc/init.d/apache2 restart
```
You will be forced to log off from a docker image.

**Comment by kp625544** [comment]
thanks, the restart one was the thing I needed. Can we include this in requirements.txt for docker runs?

**Comment by stmtstk** [comment]
We will release new S-TIP version 1.1 soon with requirements.txt requiring `six>=1.15.0'.

**Comment by kp625544** [comment]
We can close this in this case. Thanks
