### ISSUE TITLE
Error while configuring slack

### ISSUE THREAD

**Issue by kp625544** [s-tip/stip-common#55]
Error after configuring Slack Bot Token.

```
[Thu Sep 10 07:39:29.325353 2020] [wsgi:error] [pid 10:tid 140666680108800] Traceback (most recent call last):
[Thu Sep 10 07:39:29.325406 2020] [wsgi:error] [pid 10:tid 140666680108800]   File "/opt/s-tip/sns/src/daemon/slack/receive.py", line 296, in receive_slack
[Thu Sep 10 07:39:29.325413 2020] [wsgi:error] [pid 10:tid 140666680108800]     post_stip_from_slack(receive_data, slack_bot_channel_name, slack_user)
[Thu Sep 10 07:39:29.325435 2020] [wsgi:error] [pid 10:tid 140666680108800]   File "/opt/s-tip/sns/src/daemon/slack/receive.py", line 183, in post_stip_from_slack
[Thu Sep 10 07:39:29.325441 2020] [wsgi:error] [pid 10:tid 140666680108800]     user_profile = get_user_profile(user_id)
[Thu Sep 10 07:39:29.325461 2020] [wsgi:error] [pid 10:tid 140666680108800]   File "/opt/s-tip/sns/src/daemon/slack/receive.py", line 167, in get_user_profile
[Thu Sep 10 07:39:29.325476 2020] [wsgi:error] [pid 10:tid 140666680108800]     return wc.users_info(user=user_id)['user']['profile']
[Thu Sep 10 07:39:29.325508 2020] [wsgi:error] [pid 10:tid 140666680108800] AttributeError: 'NoneType' object has no attribute 'users_info'
```

Tried posting to channel through Slack API and it works, so its not a permission issue.

**Comment by stmtstk** [comment]
I checked the slack integration and it seems to work fine.

Please check the `Bot User OAuth Access Token` from slack apps (not `OAuth Access Token`).
Fill `Bot User OAuth Access Token`  at "Slack Bot Token" in SNS config page and reboot apache2 (or re-launch docker-compose up).

**Comment by kp625544** [comment]
It worked! issue was the confusion in installing and creating new apps with permission as the permission scopes have changed in Slack. Maybe we should update the wiki for the most recent Slack Bot User Token Creation. Or we can use the default Slack bot called Bots and use the API Token

**Comment by ykoji8681** [comment]
Congratulations and thank you for your feedback!
It seems that the Slack setting page has been changed  when I tested S-TIP Slack integration before.
I will check again and update the wiki.

**Comment by ykoji8681** [comment]
In a new version (v1.1) of S-TIP, it includes fix for **classic** slack app integration.

I have updated the wiki: 
https://github.com/s-tip/stip-common/wiki/Configuration#slack-integration

We found out more fixes are required for the **latest** slack app. We are planning to support the latest Slack app in a future release.
