### ISSUE TITLE
API

### ISSUE THREAD

**Issue by lysdexiafj** [s-tip/stip-common#6]
Hey team,

I am trying to use the API requests to S-TIP and getting confused with the package name parameter.

`if args.package_name is not None:
        data['package_name'] = args.package_name`

Is the package name to be included in all the requests or just the POST requests where a STIX file is uploaded?

**Comment by stmtstk** [comment]
@lysdexiafj Thanks for trying S-TIP.

It seems that you would like to post STIX to S-TIP by post_stix.py, right?
"Package_name" is an option value not required.
If you do not specify a package_name, S-TIP get a package_name from STIX data.
I hope this answer helps you.

**Comment by lysdexiafj** [comment]
Thank you, that helps my understanding :)
