### ISSUE TITLE
latest stix2 breaks things stip-rs.

### ISSUE THREAD

**Issue by sgtchains** [s-tip/stip-common#99]
On attempted new install per https://github.com/s-tip/stip-common/wiki/installation, seeing 500 error response to https://<IP>:10001 and the following tail of error_stip-rs.log

`

[Thu Oct 14 16:24:41.527681 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]   File "/opt/s-tip/rs/src/ctirs/core/mongo/documents_stix.py", line 32, in <module>
[Thu Oct 14 16:24:41.527696 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]     from stip.common.x_stip_sns import StipSns  # noqa
[Thu Oct 14 16:24:41.527713 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]   File "/opt/s-tip/common/src/stip/common/x_stip_sns.py", line 27, in <module>
[Thu Oct 14 16:24:41.527767 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]     class StipSns(object):
[Thu Oct 14 16:24:41.527786 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]   File "/usr/local/lib/python3.8/dist-packages/stix2/v21/sdo.py", line 871, in wrapper
[Thu Oct 14 16:24:41.527802 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]     return _custom_object_builder(cls, type, _properties, '2.1', _DomainObject)
[Thu Oct 14 16:24:41.527824 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]   File "/usr/local/lib/python3.8/dist-packages/stix2/custom.py", line 42, in _custom_object_builder
[Thu Oct 14 16:24:41.527840 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]     _register_object(_CustomObject, version=version)
[Thu Oct 14 16:24:41.527860 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]   File "/usr/local/lib/python3.8/dist-packages/stix2/registration.py", line 95, in _register_object
[Thu Oct 14 16:24:41.527876 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]     _validate_props(new_type._properties, version)
[Thu Oct 14 16:24:41.527895 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]   File "/usr/local/lib/python3.8/dist-packages/stix2/registration.py", line 68, in _validate_props
[Thu Oct 14 16:24:41.527912 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]     _validate_ref_props(props_map, **kwargs)
[Thu Oct 14 16:24:41.527932 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]   File "/usr/local/lib/python3.8/dist-packages/stix2/registration.py", line 44, in _validate_ref_props
[Thu Oct 14 16:24:41.527948 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055]     raise ValueError(
[Thu Oct 14 16:24:41.527973 2021] [wsgi:error] [pid 12544:tid 140617777276672] [remote 192.0.2.11:58055] ValueError: 'x_stip_sns_attachment_refs' is named like a reference list property but is not a 'ListProperty' containing a subclass of 'ReferenceProperty'.
`

It would appear that a recent commit to stix2 has broken things;  https://github.com/oasis-open/cti-python-stix2/commit/bd897c9848c6a16237cd4db479328d9e368b3e1c#diff-528e476dc60f36ab4d2cc7c17a9f01e9c27c5345b14146ee0b436cd8d9d0dce2

**Comment by sgtchains** [comment]
Post issue closure note;

Downgrading to stix2==3.0.0 allowed me to move forward... However attempting to publish to http://<ip>/feeds -> "new" resulted in "Internal Server Error: Unexpected properties for StipSns: (x_stip_sns_attachments, x_stip_sns_bundle_id)."  I do not know if this is related, if I build a new system, or if I simply do not understand how to use the system.

```
[Fri Oct 15 16:54:42.146122 2021] [wsgi:error] [pid 24353:tid 140396700808960] [remote 192.168.231.211:52444]   File "/usr/local/lib/python3.8/dist-packages/stix2/base.py", line 157, in __init__
[Fri Oct 15 16:54:42.146124 2021] [wsgi:error] [pid 24353:tid 140396700808960] [remote 192.168.231.211:52444]     raise ExtraPropertiesError(cls, custom_kwargs)
[Fri Oct 15 16:54:42.146151 2021] [wsgi:error] [pid 24353:tid 140396700808960] [remote 192.168.231.211:52444] stix2.exceptions.ExtraPropertiesError: Unexpected properties for StipSns: (x_stip_sns_attachments, x_stip_sns_bundle_id).
[Fri Oct 15 16:54:42.169710 2021] [wsgi:error] [pid 24353:tid 140396700808960] [remote 192.168.231.211:52444] Internal Server Error: /feeds/post/
```

If I get time later, I'll start from scratch.

**Comment by stmtstk** [comment]
Thanks for your report.

> Testing showed that the install script was complaining with 'ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.' and also 'ERROR: pymisp 2.4.138 has requirement requests<3.0.0,>=2.25.0, but you'll have requests 2.22.0 which is incompatible.' So before install;

I tried scratch-installing S-TIP on `Ubuntu20.04`. At that time, I changed the version limit of `pymisp` in requirement_rs.txt from `pymisp<2.4.140` to `pymisp`.
The installation was successful and I confirmed the startup. The version information is below.

```
pymisp==2.4.138
requests==2.22.0
```

I didn't get the error due to the version of `pymisp`.
I am not sure why you get the error.
It may be more appropriate to ask in the `pymisp` issue.
